#!/usr/bin/env bash
# build_all.sh — Build course examples through:
#   1) g++ native + MaiaCpp (for *.cpp)
#   2) MaiaJS pipeline for explicit JS ports (*.port.js / js_ports/*.js)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
MAIAJS_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd -P)"
PROJECTS_ROOT="$(cd "$MAIAJS_ROOT/.." && pwd -P)"

resolve_tool() {
    local local_path="$1"
    local sibling_path="$2"
    if [[ -f "$local_path" ]]; then
        echo "$local_path"
        return 0
    fi
    if [[ -f "$sibling_path" ]]; then
        echo "$sibling_path"
        return 0
    fi
    return 1
}

WEBCPP="$(resolve_tool "$MAIAJS_ROOT/maiacpp/bin/webcpp.sh" "$PROJECTS_ROOT/maiacpp/bin/webcpp.sh" || true)"
WEBJS="$(resolve_tool "$MAIAJS_ROOT/bin/webjs.sh" "$PROJECTS_ROOT/maiajs/bin/webjs.sh" || true)"

VERBOSE=0
FILTER=""
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=1 ;;
        *)            FILTER="$arg" ;;
    esac
done

if [[ -z "$WEBCPP" || ! -f "$WEBCPP" ]]; then
    echo "ERROR: webcpp.sh not found" >&2
    exit 1
fi
if [[ -z "$WEBJS" || ! -f "$WEBJS" ]]; then
    echo "ERROR: webjs.sh not found" >&2
    exit 1
fi

GPP_PASS=0
GPP_FAIL=0
MAIACPP_PASS=0
MAIACPP_FAIL=0
MAIAJS_PASS=0
MAIAJS_FAIL=0
MAIAJS_NO_PORTS=0

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

is_js_port_file() {
    local src="$1"
    [[ -f "$src" ]] || return 1
    case "$(basename "$src")" in
        node-runner.js|browser-memory-file-store.js) return 1 ;;
    esac
    if is_generated_webc_js "$src"; then
        return 1
    fi
    return 0
}

collect_js_ports_for_dir() {
    local test_dir="$1"
    local src
    shopt -s nullglob
    for src in "$test_dir"*.port.js "$test_dir"js_ports/*.js; do
        is_js_port_file "$src" && printf '%s\n' "$src"
    done
    shopt -u nullglob
}

build_gpp() {
    local src="$1"
    local stem="$(basename "${src%.cpp}")"
    local dir="$(dirname "$src")"
    local out="$dir/$stem"

    if [[ "$VERBOSE" -eq 1 ]]; then
        g++ -std=c++11 -o "$out" "$src"
    else
        g++ -std=c++11 -o "$out" "$src" 2>/dev/null
    fi

    local rc=$?
    if [[ "$rc" -ne 0 ]]; then
        echo "    g++    FAILED (exit $rc)"
        GPP_FAIL=$((GPP_FAIL + 1))
        return
    fi

    echo "    g++    OK -> $(basename "$out")"
    GPP_PASS=$((GPP_PASS + 1))
}

build_maiacpp() {
    local src="$1"
    local dir="$(dirname "$src")"
    local stem="$(basename "${src%.cpp}")"
    local c_out="${src%.cpp}.c"
    local wat_out="${src%.cpp}.wat"
    local dist_dir="$dir/dist"

    local cmd=("$WEBCPP" "$src" --c-out "$c_out" --wat-out "$wat_out" --dist --out-dir "$dist_dir" --name "$stem")
    if [[ "$VERBOSE" -eq 1 ]]; then
        "${cmd[@]}"
    else
        if ! "${cmd[@]}" 2>&1 | grep -E '^\[(webcpp|webc)\]|ERROR|error:'; then
            true
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    MaiaCpp FAILED (exit $rc)"
        MAIACPP_FAIL=$((MAIACPP_FAIL + 1))
        return
    fi

    local wasm_file="$dist_dir/$stem.wasm"
    local size_wasm=0
    if [[ -f "$wasm_file" ]]; then
        size_wasm="$(wc -c < "$wasm_file")"
    fi

    echo "    MaiaCpp OK — C: $(basename "$c_out")  WASM: ${size_wasm}B"
    MAIACPP_PASS=$((MAIACPP_PASS + 1))
}

build_maiajs_port() {
    local src="$1"
    local dir="$(dirname "$src")"
    local stem="$(basename "${src%.js}")"
    local dist_dir="$dir/dist_js"

    local cmd=("$WEBJS" "$src" --dist --out-dir "$dist_dir" --name "$stem")
    if [[ "$VERBOSE" -eq 1 ]]; then
        MAIAJS_SKIP_TESTS=1 "${cmd[@]}"
    else
        if ! MAIAJS_SKIP_TESTS=1 "${cmd[@]}" 2>&1 | grep -E '^\[(webjs|webcpp|webc)\]|ERROR|error:'; then
            true
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    MaiaJS  FAILED (exit $rc)"
        MAIAJS_FAIL=$((MAIAJS_FAIL + 1))
        return
    fi

    local root_dist="$MAIAJS_ROOT/dist"
    local root_wasm="$root_dist/$stem.wasm"
    local root_js_wrapper="$root_dist/$stem.js"
    local root_runner_js="$root_dist/node-runner.js"
    local root_runner_sh="$root_dist/node-runner.sh"
    local root_manifest="$root_dist/manifest.json"

    if [[ -f "$root_wasm" ]]; then
        mkdir -p "$dist_dir"
        cp -f "$root_wasm" "$dist_dir/$stem.wasm"
        [[ -f "$root_js_wrapper" ]] && cp -f "$root_js_wrapper" "$dist_dir/$stem.js"
        [[ -f "$root_runner_js" ]] && cp -f "$root_runner_js" "$dist_dir/node-runner.js"
        [[ -f "$root_runner_sh" ]] && cp -f "$root_runner_sh" "$dist_dir/node-runner.sh"
        [[ -f "$root_manifest" ]] && cp -f "$root_manifest" "$dist_dir/manifest.json"

        local lib
        for lib in "$root_dist"/*.wasm "$root_dist"/*.js; do
            [[ -f "$lib" ]] || continue
            cp -f "$lib" "$dist_dir/$(basename "$lib")"
        done
    fi

    local wasm_file="$dist_dir/$stem.wasm"
    if [[ -f "$wasm_file" ]]; then
        local size_wasm
        size_wasm="$(wc -c < "$wasm_file")"
        echo "    MaiaJS  OK — WASM: ${size_wasm}B"
        MAIAJS_PASS=$((MAIAJS_PASS + 1))
    else
        echo "    MaiaJS  FAILED — dist output missing $stem.wasm"
        MAIAJS_FAIL=$((MAIAJS_FAIL + 1))
    fi
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        echo ""
        echo "==> $dir_name/$stem.cpp"
        build_gpp "$src"
        build_maiacpp "$src"
    done

    local_has_port=0
    while IFS= read -r src; do
        [[ -n "$src" ]] || continue
        local_has_port=1
        echo ""
        echo "==> $dir_name/$(basename "$src")"
        build_maiajs_port "$src"
    done < <(collect_js_ports_for_dir "$test_dir")

    if [[ "$local_has_port" -eq 0 ]]; then
        echo ""
        echo "==> $dir_name"
        echo "    MaiaJS  SKIP — no JS ports found (expected *.port.js or js_ports/*.js)"
        MAIAJS_NO_PORTS=$((MAIAJS_NO_PORTS + 1))
    fi
done

echo ""
echo "========================================"
echo "g++         : $GPP_PASS built, $GPP_FAIL failed"
echo "MaiaCpp     : $MAIACPP_PASS built, $MAIACPP_FAIL failed"
echo "MaiaJS ports: $MAIAJS_PASS built, $MAIAJS_FAIL failed"
echo "MaiaJS ports: $MAIAJS_NO_PORTS dirs without JS ports"
echo "========================================"

if [[ "$GPP_FAIL" -gt 0 || "$MAIACPP_FAIL" -gt 0 || "$MAIAJS_FAIL" -gt 0 ]]; then
    exit 1
fi
