#!/usr/bin/env bash
# build_all.sh — Build course examples through all available pipelines:
#   1) g++ native (for .cpp)
#   2) MaiaCpp -> MaiaC (for .cpp)
#   3) MaiaJS -> dist/wasm   (for .js)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
MAIAJS_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd -P)"
PROJECTS_ROOT="$(cd "$MAIAJS_ROOT/.." && pwd -P)"

resolve_tool() {
    local local_path="$1"
    local sibling_path="$2"
    if [[ -f "$local_path" ]]; then
        echo "$local_path"
        return 0
    fi
    if [[ -f "$sibling_path" ]]; then
        echo "$sibling_path"
        return 0
    fi
    return 1
}

WEBCPP="$(resolve_tool "$MAIAJS_ROOT/maiacpp/bin/webcpp.sh" "$PROJECTS_ROOT/maiacpp/bin/webcpp.sh" || true)"
WEBJS="$(resolve_tool "$MAIAJS_ROOT/bin/webjs.sh" "$PROJECTS_ROOT/maiajs/bin/webjs.sh" || true)"

VERBOSE=0
FILTER=""
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=1 ;;
        *)            FILTER="$arg" ;;
    esac
done

GPP_PASS=0
GPP_FAIL=0
MAIACPP_PASS=0
MAIACPP_FAIL=0
MAIACPP_SKIP=0
MAIAJS_PASS=0
MAIAJS_FAIL=0
MAIAJS_SKIP=0
MAIAJS_UNSUPPORTED=0

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

# ── compile with g++ ─────────────────────────────────────────────────────────
build_gpp() {
    local src="$1"
    local stem
    stem="$(basename "${src%.cpp}")"
    local dir
    dir="$(dirname "$src")"
    local out="$dir/$stem"

    if [[ "$VERBOSE" -eq 1 ]]; then
        g++ -std=c++11 -o "$out" "$src"
    else
        g++ -std=c++11 -o "$out" "$src" 2>/dev/null
    fi

    local rc=$?
    if [[ "$rc" -ne 0 ]]; then
        echo "    g++    FAILED (exit $rc)"
        GPP_FAIL=$((GPP_FAIL + 1))
        return 1
    else
        echo "    g++    OK → $(basename "$out")"
        GPP_PASS=$((GPP_PASS + 1))
        return 0
    fi
}

# ── transpile with MaiaCpp ────────────────────────────────────────────────────
build_maiacpp() {
    local src="$1"
    local dir
    dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.cpp}")"
    local c_out="${src%.cpp}.c"
    local wat_out="${src%.cpp}.wat"
    local dist_dir="$dir/dist"

    if [[ ! -x "$WEBCPP" && ! -f "$WEBCPP" ]]; then
        echo "    MaiaCpp SKIP — webcpp.sh not found"
        MAIACPP_SKIP=$((MAIACPP_SKIP + 1))
        return
    fi

    local cmd=("$WEBCPP" "$src"
        --c-out   "$c_out"
        --wat-out "$wat_out"
        --dist    --out-dir "$dist_dir"
        --name    "$stem")

    if [[ "$VERBOSE" -eq 1 ]]; then
        "${cmd[@]}"
    else
        if ! "${cmd[@]}" 2>&1 | grep -E '^\[(webcpp|webc)\]|ERROR|error:' ; then
            true
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    MaiaCpp FAILED (exit $rc)"
        MAIACPP_FAIL=$((MAIACPP_FAIL + 1))
        return
    fi

    local size_wasm=0
    local wasm_file="${src%.cpp}.wasm"
    if [[ -f "$wasm_file" ]]; then
        size_wasm="$(wc -c < "$wasm_file")"
        # Keep dist self-contained for run_all.sh/node-runner default path.
        cp -f "$wasm_file" "$dist_dir/$stem.wasm"
    fi

    echo "    MaiaCpp OK — C: $(basename "$c_out")  WASM: ${size_wasm}B"
    MAIACPP_PASS=$((MAIACPP_PASS + 1))
}

build_maiajs() {
    local src="$1"
    local dir
    dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.js}")"
    local dist_dir="$dir/dist_js"

    if [[ -z "$WEBJS" || ! -f "$WEBJS" ]]; then
        echo "    MaiaJS  SKIP — webjs.sh not found"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    local cmd=("$WEBJS" "$src"
        --dist --out-dir "$dist_dir"
        --name "$stem")

    if [[ "$VERBOSE" -eq 1 ]]; then
        "${cmd[@]}"
    else
        if ! "${cmd[@]}" 2>&1 | grep -E '^\[(webjs|webcpp|webc)\]|ERROR|error:' ; then
            true
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    MaiaJS  FAILED (exit $rc)"
        MAIAJS_FAIL=$((MAIAJS_FAIL + 1))
        return
    fi

    local size_wasm=0
    local runner_file="$dist_dir/node-runner.sh"
    local wasm_file="$dist_dir/$stem.wasm"
    if [[ -f "$wasm_file" && -f "$runner_file" ]]; then
        size_wasm="$(wc -c < "$wasm_file")"
    else
        echo "    MaiaJS  SKIP — dist output missing (node-runner.sh or $stem.wasm)"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    echo "    MaiaJS  OK — WASM: ${size_wasm}B"
    MAIAJS_PASS=$((MAIAJS_PASS + 1))
}

# ── main loop ─────────────────────────────────────────────────────────────────
for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        echo ""
        echo "==> $dir_name/$stem.cpp"
        build_gpp    "$src"
        build_maiacpp "$src"
    done

    for src in "$test_dir"*.js; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.js}")"
        if is_generated_webc_js "$src"; then
            echo ""
            echo "==> $dir_name/$stem.js"
            echo "    MaiaJS  SKIP — generated webc artifact (unsupported source class)"
            MAIAJS_UNSUPPORTED=$((MAIAJS_UNSUPPORTED + 1))
            continue
        fi
        echo ""
        echo "==> $dir_name/$stem.js"
        build_maiajs "$src"
    done
done

echo ""
echo "========================================"
echo "g++     : $GPP_PASS built, $GPP_FAIL failed"
echo "MaiaCpp : $MAIACPP_PASS built, $MAIACPP_FAIL failed, $MAIACPP_SKIP skipped"
echo "MaiaJS  : $MAIAJS_PASS built, $MAIAJS_FAIL failed, $MAIAJS_SKIP skipped"
echo "MaiaJS  : $MAIAJS_UNSUPPORTED skipped as unsupported source class"
echo "========================================"

if [[ "$GPP_FAIL" -gt 0 || "$MAIACPP_FAIL" -gt 0 || "$MAIAJS_FAIL" -gt 0 ]]; then
    exit 1
fi
