#!/usr/bin/env bash
# run_all.sh — Execute course examples and compare outputs between:
#   g++ native, MaiaCpp WASM, and MaiaJS WASM.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

# Cross-platform timeout wrapper (macOS lacks GNU 'timeout')
_run_timed() {
    local secs=$1; shift
    if command -v timeout &>/dev/null; then
        timeout "$secs" "$@"
    elif command -v gtimeout &>/dev/null; then
        gtimeout "$secs" "$@"
    else
        # No timeout binary available — programs with a complete input.txt won't hang
        "$@"
    fi
}

FILTER="${1:-}"
WASM_TIMEOUT="${WASM_TIMEOUT:-10}"
STRICT="${STRICT:-1}"

PASS=0
FAIL=0
SKIP=0
INTERACTIVE=0
MAIACPP_PASS=0
MAIACPP_FAIL=0
MAIACPP_SKIP=0
MAIAJS_PASS=0
MAIAJS_FAIL=0
MAIAJS_SKIP=0
MAIAJS_UNSUPPORTED=0

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

normalize_output() {
    # Keep semantic output while masking unstable address-like values.
    printf '%s\n' "$1" \
        | LC_ALL=C tr -d '\000' \
        | sed -E 's/0x[0-9a-fA-F]+/<ADDR>/g; s/[0-9]{7,}/<NUM>/g' \
        | awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}'
}

run_maiajs() {
    local test_dir="$1"
    local stem="$2"
    local input_file="$3"
    local ref_norm="$4"
    local src_js="$test_dir/$stem.js"
    if [[ -f "$src_js" ]] && is_generated_webc_js "$src_js"; then
        echo "    MaiaJS  SKIP — generated webc artifact (unsupported source class)"
        MAIAJS_UNSUPPORTED=$((MAIAJS_UNSUPPORTED + 1))
        return
    fi


    local runner="$test_dir/dist_js/node-runner.sh"
    local wasm_file="$test_dir/dist_js/$stem.wasm"
    local js_expected="$test_dir/${stem}.js_expected_output.txt"
    local expected="$test_dir/${stem}.expected_output.txt"

    if [[ ! -f "$runner" || ! -f "$wasm_file" ]]; then
        echo "    MaiaJS  SKIP — WASM dist not found (run build_all.sh first)"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    local wasm_raw
    if [[ -f "$input_file" ]]; then
        wasm_raw="$(_run_timed "$WASM_TIMEOUT" bash "$runner" "$wasm_file" < "$input_file" 2>/dev/null)" || true
    else
        wasm_raw="$(echo '' | _run_timed "$WASM_TIMEOUT" bash "$runner" "$wasm_file" 2>/dev/null)" || true
    fi

    local wasm_out
    wasm_out="$(printf '%s\n' "$wasm_raw" | sed '/^\[node-runner\] program returned:/d')"
    local wasm_norm
    wasm_norm="$(normalize_output "$wasm_out")"

    local ref_text="$ref_norm"
    if [[ -f "$js_expected" ]]; then
        ref_text="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$js_expected")"
    elif [[ -f "$expected" ]]; then
        ref_text="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
    fi

    if [[ -z "$ref_text" ]]; then
        echo "    MaiaJS  SKIP — no reference output available"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    if diff <(printf '%s\n' "$ref_text") <(printf '%s\n' "$wasm_norm") > /dev/null 2>&1; then
        echo "    MaiaJS  PASS"
        MAIAJS_PASS=$((MAIAJS_PASS + 1))
    else
        echo "    MaiaJS  FAIL — output mismatch"
        echo "    ┌── reference ─────────────────────────────────────"
        printf '%s\n' "$ref_text" | sed 's/^/    │ /'
        echo "    ├── MaiaJS ────────────────────────────────────────"
        printf '%s\n' "$wasm_norm" | sed 's/^/    │ /'
        echo "    └──────────────────────────────────────────────────"
        MAIAJS_FAIL=$((MAIAJS_FAIL + 1))
    fi
}

run_one() {
    local test_dir="$1"
    local stem="$2"
    local binary="$test_dir/$stem"
    local runner_sh="$test_dir/dist/node-runner.sh"
    local runner_js="$test_dir/dist/node-runner.js"
    local wasm_file="$test_dir/dist/$stem.wasm"
    if [[ ! -f "$wasm_file" ]]; then
        wasm_file="$test_dir/$stem.wasm"
    fi
    local expected="$test_dir/${stem}.expected_output.txt"
    local input_file="$test_dir/${stem}.input.txt"

    echo ""
    echo "--> $(basename "$test_dir")/$stem"

    # ── check g++ binary ──────────────────────────────────────────────────────
    if [[ ! -x "$binary" ]]; then
        echo "    SKIP — g++ binary not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi

    # ── run g++ binary ────────────────────────────────────────────────────────
    local gpp_out
    if [[ -f "$input_file" ]]; then
        gpp_out="$("$binary" < "$input_file" 2>/dev/null)" || true
    else
        # Programs that read stdin will exit immediately with empty input
        gpp_out="$(echo '' | "$binary" 2>/dev/null)" || true
    fi

    local gpp_norm
    gpp_norm="$(normalize_output "$gpp_out")"

    # ── compare with expected_output.txt ─────────────────────────────────────
    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$gpp_norm") <(printf '%s\n' "$expected_norm") > /dev/null 2>&1; then
            echo "    g++    PASS (matches expected_output.txt)"
            PASS=$((PASS + 1))
        else
            echo "    g++    FAIL — output mismatch vs expected_output.txt"
            echo "    ┌── expected ──────────────────────────────────────"
            printf '%s\n' "$expected_norm" | sed 's/^/    │ /'
            echo "    ├── actual ────────────────────────────────────────"
            printf '%s\n' "$gpp_norm"      | sed 's/^/    │ /'
            echo "    └─────────────────────────────────────────────────"
            FAIL=$((FAIL + 1))
        fi
    else
        echo "    g++    OUTPUT (no expected_output.txt):"
        if [[ -n "$gpp_norm" ]]; then
            printf '%s\n' "$gpp_norm" | sed 's/^/    > /'
        else
            echo "    > (no output — program may require interactive input)"
            INTERACTIVE=$((INTERACTIVE + 1))
        fi
    fi

    # ── compare g++ vs MaiaCpp WASM ──────────────────────────────────────────
    if [[ -f "$runner_sh" || -f "$runner_js" ]]; then
        local wasm_raw
        # Pass the specific WASM file and the same stdin used for g++.
        if [[ -f "$wasm_file" ]]; then
            if [[ -f "$input_file" ]]; then
                if [[ -f "$runner_sh" ]]; then
                    wasm_raw="$(_run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" < "$input_file" 2>/dev/null)" || true
                else
                    wasm_raw="$(_run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" < "$input_file" 2>/dev/null)" || true
                fi
            else
                if [[ -f "$runner_sh" ]]; then
                    wasm_raw="$(echo '' | _run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
                else
                    wasm_raw="$(echo '' | _run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" 2>/dev/null)" || true
                fi
            fi
        else
            # WASM not compiled (0-byte or missing) — skip comparison
            echo "    MaiaCpp SKIP — WASM binary not found (stub-fallback or build error)"
            MAIACPP_SKIP=$((MAIACPP_SKIP + 1))
            return
        fi
        local wasm_out
        wasm_out="$(printf '%s\n' "$wasm_raw" | sed '/^\[node-runner\] program returned:/d')"
        local wasm_norm
        wasm_norm="$(normalize_output "$wasm_out")"

        # If a WASM-specific expected output exists, compare against it instead of g++
        local wasm_expected_file="$test_dir/${stem}.wasm_expected_output.txt"
        local wasm_ref_norm
        if [[ -f "$wasm_expected_file" ]]; then
            wasm_ref_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$wasm_expected_file")"
        else
            wasm_ref_norm="$gpp_norm"
        fi

        if diff <(printf '%s\n' "$wasm_ref_norm") <(printf '%s\n' "$wasm_norm") > /dev/null 2>&1; then
            echo "    MaiaCpp PASS (matches g++ output)"
            MAIACPP_PASS=$((MAIACPP_PASS + 1))
        else
            local generated_c="$test_dir/$stem.c"
            local classification="output-mismatch"
            if [[ -f "$generated_c" ]] && grep -q "stub-fallback" "$generated_c"; then
                classification="stub-fallback (semantic gap)"
            fi
            echo "    MaiaCpp FAIL — $classification"
            if [[ -f "$wasm_expected_file" ]]; then
                echo "    ┌── expected (wasm_expected_output.txt) ──────────"
                printf '%s\n' "$wasm_ref_norm" | sed 's/^/    │ /'
            else
                echo "    ┌── g++ ──────────────────────────────────────────"
                printf '%s\n' "$gpp_norm"  | sed 's/^/    │ /'
            fi
            echo "    ├── MaiaCpp ──────────────────────────────────────"
            printf '%s\n' "$wasm_norm" | sed 's/^/    │ /'
            echo "    └─────────────────────────────────────────────────"
            MAIACPP_FAIL=$((MAIACPP_FAIL + 1))
        fi
    else
        echo "    MaiaCpp SKIP — WASM dist not found (run build_all.sh first)"
        MAIACPP_SKIP=$((MAIACPP_SKIP + 1))
    fi

    run_maiajs "$test_dir" "$stem" "$input_file" "$gpp_norm"
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        run_one "$test_dir" "$stem"
    done
done

# Run JS-only examples (without a matching .cpp file).
for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.js; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.js}")"
        if [[ -f "$test_dir/$stem.cpp" ]]; then
            continue
        fi
        echo ""
        echo "--> $(basename "$test_dir")/$stem [js-only]"
        run_maiajs "$test_dir" "$stem" "$test_dir/${stem}.input.txt" ""
    done
done

echo ""
echo "========================================"
echo "g++ results : $PASS passed  /  $FAIL failed  /  $SKIP skipped"
echo "MaiaCpp WASM: $MAIACPP_PASS passed  /  $MAIACPP_FAIL failed  /  $MAIACPP_SKIP skipped"
echo "MaiaJS WASM : $MAIAJS_PASS passed  /  $MAIAJS_FAIL failed  /  $MAIAJS_SKIP skipped"
echo "MaiaJS WASM : $MAIAJS_UNSUPPORTED skipped as unsupported source class"
echo "Programs with no expected_output and no input.txt: $INTERACTIVE"
echo "========================================"

if [[ "$FAIL" -gt 0 || "$MAIACPP_FAIL" -gt 0 || "$MAIAJS_FAIL" -gt 0 ]]; then
    exit 1
fi

if [[ "$STRICT" == "1" && ( "$SKIP" -gt 0 || "$MAIACPP_SKIP" -gt 0 || "$MAIAJS_SKIP" -gt 0 ) ]]; then
    echo "STRICT mode: failing because at least one test was skipped."
    exit 1
fi
