#!/usr/bin/env bash
# run_all.sh — Execute course examples and compare outputs between:
#   g++ native, MaiaCpp WASM, and MaiaJS JS ports (when available).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
FILTER="${1:-}"
WASM_TIMEOUT="${WASM_TIMEOUT:-10}"
STRICT="${STRICT:-1}"

PASS=0
FAIL=0
SKIP=0
MAIACPP_PASS=0
MAIACPP_FAIL=0
MAIACPP_SKIP=0
MAIAJS_PASS=0
MAIAJS_FAIL=0
MAIAJS_SKIP=0
MAIAJS_NO_PORTS=0

run_timed() {
    local secs="$1"
    shift
    if command -v timeout >/dev/null 2>&1; then
        timeout "$secs" "$@"
    elif command -v gtimeout >/dev/null 2>&1; then
        gtimeout "$secs" "$@"
    else
        "$@"
    fi
}

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

is_js_port_file() {
    local src="$1"
    [[ -f "$src" ]] || return 1
    case "$(basename "$src")" in
        node-runner.js|browser-memory-file-store.js) return 1 ;;
    esac
    if is_generated_webc_js "$src"; then
        return 1
    fi
    return 0
}

normalize_output() {
    printf '%s\n' "$1" \
        | LC_ALL=C tr -d '\000' \
    | LC_ALL=C sed -E 's/0x[0-9a-fA-F]+/<ADDR>/g; s/[0-9]{7,}/<NUM>/g' \
        | awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}'
}

collect_js_ports_for_dir() {
    local test_dir="$1"
    local src
    shopt -s nullglob
    for src in "$test_dir"*.port.js "$test_dir"js_ports/*.js; do
        is_js_port_file "$src" && printf '%s\n' "$src"
    done
    shopt -u nullglob
}

run_maiajs_port() {
    local src="$1"
    local input_file="$2"
    local gpp_norm="$3"

    local test_dir
    test_dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.js}")"
    local runner="$test_dir/dist_js/node-runner.sh"
    local wasm_file="$test_dir/dist_js/$stem.wasm"
    local js_expected="$test_dir/${stem}.js_expected_output.txt"

    echo ""
    echo "--> $(basename "$test_dir")/$stem [js-port]"

    if [[ ! -f "$runner" || ! -f "$wasm_file" ]]; then
        echo "    MaiaJS  SKIP — JS port dist not found (run build_all.sh first)"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    local wasm_raw
    if [[ -f "$input_file" ]]; then
        wasm_raw="$(run_timed "$WASM_TIMEOUT" bash "$runner" "$wasm_file" < "$input_file" 2>/dev/null)" || true
    else
        wasm_raw="$(echo '' | run_timed "$WASM_TIMEOUT" bash "$runner" "$wasm_file" 2>/dev/null)" || true
    fi

    local wasm_out
    wasm_out="$(printf '%s\n' "$wasm_raw" | sed '/^\[node-runner\] program returned:/d')"
    local wasm_norm
    wasm_norm="$(normalize_output "$wasm_out")"

    local ref_text="$gpp_norm"
    if [[ -f "$js_expected" ]]; then
        ref_text="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$js_expected")"
    fi

    if [[ -z "$ref_text" ]]; then
        echo "    MaiaJS  SKIP — no reference output"
        MAIAJS_SKIP=$((MAIAJS_SKIP + 1))
        return
    fi

    if diff <(printf '%s\n' "$ref_text") <(printf '%s\n' "$wasm_norm") >/dev/null 2>&1; then
        echo "    MaiaJS  PASS"
        MAIAJS_PASS=$((MAIAJS_PASS + 1))
    else
        echo "    MaiaJS  FAIL — output mismatch"
        MAIAJS_FAIL=$((MAIAJS_FAIL + 1))
    fi
}

run_cpp_one() {
    local test_dir="$1"
    local stem="$2"
    local binary="$test_dir/$stem"
    local runner_sh="$test_dir/dist/node-runner.sh"
    local runner_js="$test_dir/dist/node-runner.js"
    local wasm_file="$test_dir/dist/$stem.wasm"
    if [[ ! -f "$wasm_file" ]]; then
        wasm_file="$test_dir/$stem.wasm"
    fi
    local expected="$test_dir/${stem}.expected_output.txt"
    local input_file="$test_dir/${stem}.input.txt"

    echo ""
    echo "--> $(basename "$test_dir")/$stem [cpp]"

    if [[ ! -x "$binary" ]]; then
        echo "    SKIP — g++ binary not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi

    local gpp_out
    if [[ -f "$input_file" ]]; then
        gpp_out="$("$binary" < "$input_file" 2>/dev/null)" || true
    else
        gpp_out="$(echo '' | "$binary" 2>/dev/null)" || true
    fi

    local gpp_norm
    gpp_norm="$(normalize_output "$gpp_out")"

    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$gpp_norm") <(printf '%s\n' "$expected_norm") >/dev/null 2>&1; then
            echo "    g++    PASS"
            PASS=$((PASS + 1))
        else
            echo "    g++    FAIL — output mismatch"
            FAIL=$((FAIL + 1))
        fi
    else
        echo "    g++    SKIP — no expected_output reference"
        SKIP=$((SKIP + 1))
    fi

    if [[ -f "$runner_sh" || -f "$runner_js" ]]; then
        if [[ ! -f "$wasm_file" ]]; then
            echo "    MaiaCpp SKIP — WASM binary not found"
            MAIACPP_SKIP=$((MAIACPP_SKIP + 1))
        else
            local wasm_raw
            if [[ -f "$input_file" ]]; then
                if [[ -f "$runner_sh" ]]; then
                    wasm_raw="$(run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" < "$input_file" 2>/dev/null)" || true
                else
                    wasm_raw="$(run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" < "$input_file" 2>/dev/null)" || true
                fi
            else
                if [[ -f "$runner_sh" ]]; then
                    wasm_raw="$(echo '' | run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
                else
                    wasm_raw="$(echo '' | run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" 2>/dev/null)" || true
                fi
            fi

            local wasm_out
            wasm_out="$(printf '%s\n' "$wasm_raw" | sed '/^\[node-runner\] program returned:/d')"
            local wasm_norm
            wasm_norm="$(normalize_output "$wasm_out")"

            local wasm_ref_norm="$gpp_norm"
            local wasm_expected_file="$test_dir/${stem}.wasm_expected_output.txt"
            if [[ -f "$wasm_expected_file" ]]; then
                wasm_ref_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$wasm_expected_file")"
            fi

            if diff <(printf '%s\n' "$wasm_ref_norm") <(printf '%s\n' "$wasm_norm") >/dev/null 2>&1; then
                echo "    MaiaCpp PASS"
                MAIACPP_PASS=$((MAIACPP_PASS + 1))
            else
                echo "    MaiaCpp FAIL — output mismatch"
                MAIACPP_FAIL=$((MAIACPP_FAIL + 1))
            fi
        fi
    else
        echo "    MaiaCpp SKIP — WASM dist not found (run build_all.sh first)"
        MAIACPP_SKIP=$((MAIACPP_SKIP + 1))
    fi

    local port_file="$test_dir/${stem}.port.js"
    if is_js_port_file "$port_file"; then
        run_maiajs_port "$port_file" "$input_file" "$gpp_norm"
    else
        MAIAJS_NO_PORTS=$((MAIAJS_NO_PORTS + 1))
    fi
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        run_cpp_one "$test_dir" "$stem"
    done

    while IFS= read -r src; do
        [[ -n "$src" ]] || continue
        if [[ -f "${src%.js}.cpp" ]]; then
            continue
        fi
        run_maiajs_port "$src" "$test_dir/$(basename "${src%.js}").input.txt" ""
    done < <(collect_js_ports_for_dir "$test_dir")
done

echo ""
echo "========================================"
echo "g++ results : $PASS passed  /  $FAIL failed  /  $SKIP skipped"
echo "MaiaCpp WASM: $MAIACPP_PASS passed  /  $MAIACPP_FAIL failed  /  $MAIACPP_SKIP skipped"
echo "MaiaJS ports: $MAIAJS_PASS passed  /  $MAIAJS_FAIL failed  /  $MAIAJS_SKIP skipped"
echo "MaiaJS ports: $MAIAJS_NO_PORTS cpp files without matching .port.js"
echo "========================================"

if [[ "$FAIL" -gt 0 || "$MAIACPP_FAIL" -gt 0 || "$MAIAJS_FAIL" -gt 0 ]]; then
    exit 1
fi

if [[ "$STRICT" == "1" && ( "$SKIP" -gt 0 || "$MAIACPP_SKIP" -gt 0 || "$MAIAJS_SKIP" -gt 0 ) ]]; then
    echo "STRICT mode: failing because at least one test was skipped."
    exit 1
fi
