// Auto-generated by ecmascript-compiler.js
// Source: test.js
// Host-call map: fn -> __fn
// Host-call map: c.getValue -> __c__getValue
// Host-call map: box.setAt -> __box__setAt
// Host-call map: box.setAt -> __box__setAt
// Host-call map: box.at -> __box__at
// Host-call map: box.at -> __box__at
// Host-call map: d.value -> __d__value
// Host-call map: a.getValue -> __a__getValue
// Host-call map: p.getValue -> __p__getValue
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log

extern void __fn(void*, void*);
extern void __c__getValue(void);
extern void __box__setAt(double, double);
extern void __box__at(double);
extern void __d__value(void);
extern void __a__getValue(void);
extern void __p__getValue(void);
extern int __console__log(const char*);

/* shared local runtime helpers for literal/lambda fallbacks */
#ifndef MAIA_RUNTIME_LOCAL_HELPERS_DEFINED
#define MAIA_RUNTIME_LOCAL_HELPERS_DEFINED 1
struct __maia_runtime_value {
  int tag;
  int a;
  int b;
  int c;
};
static void* __maia_runtime_alloc_value(int tag, int a, int b, int c) {
  __maia_runtime_value* v = new __maia_runtime_value();
  v->tag = tag;
  v->a = a;
  v->b = b;
  v->c = c;
  return (void*)v;
}
#endif

/* array literal runtime hooks (runtime-provided) */
extern void* __maia_arr_literal0(void);

/* local fallback runtime for array literal hooks */
#ifndef MAIA_RUNTIME_PROVIDES_ARRAY_HOOKS
void* __maia_arr_literal0(void) {
  return __maia_runtime_alloc_value(2, 0, 0, 0);
}
#endif

struct C {
  int value;
  C(int x) {
    this->value = x;
  }
  int getValue(void) {
    return (int)(this->value);
  }
};

struct Box {
  int d0;
  int d1;
  int d2;
  int d3;
  Box(void) {
    this->d0 = 0;
    this->d1 = 0;
    this->d2 = 0;
    this->d3 = 0;
  }
  int at(int i) {
    if (i == 0) {
      return (int)(this->d0);
    }
    if (i == 1) {
      return (int)(this->d1);
    }
    if (i == 2) {
      return (int)(this->d2);
    }
    return (int)(this->d3);
  }
  int setAt(int i, int v) {
    if (i == 0) {
      this->d0 = v;
      return 0;
    }
    if (i == 1) {
      this->d1 = v;
      return 0;
    }
    if (i == 2) {
      this->d2 = v;
      return 0;
    }
    this->d3 = v;
  }
};

struct BBase {
  BBase(void) {
  }
};

struct DDerived {
  int number;
  // extends BBase (inheritance semantics not yet lowered)
  DDerived(int n) {
    (void)0;
    this->number = n;
  }
  int value(void) {
    return (int)(this->number);
  }
};

struct P {
  int val;
  P(int x) {
    this->val = x;
  }
  int getValue(void) {
    return (int)(this->val);
  }
};

struct PointRec {
  int x;
  int y;
  PointRec(int x, int y) {
    this->x = x;
    this->y = y;
  }
};

int add(int a, int b);
int multiply(int a, int b);
int execute(int a, int b, int fn);
int runClassTests(void);
int runBoxTests(void);
int runFunctionRefTests(void);
int runInheritanceTests(void);
int runNewTests(void);
int runCoutStressTests(void);
int runForCoutTest(void);
int bubbleSort(int array);
int runArrayStressTests(void);
int runProgram(void);

int add(int a, int b) {
  return (int)(a + b);
}

int multiply(int a, int b) {
  return (int)(a * b);
}

int execute(int a, int b, int fn) {
  return (int)(__fn(a, b));
}

int runClassTests(void) {
  const void* c = __new__C(42);
  return 0;
}

int runBoxTests(void) {
  const void* box = __new__Box();
  __box__setAt(0, 10);
  __box__setAt(1, 20);
  return 0;
}

int runFunctionRefTests(void) {
  const void* s = execute(7, 3, add);
  const void* m = execute(7, 3, multiply);
  return 0;
}

int runInheritanceTests(void) {
  const void* d = __new__DDerived(15);
  const void* isBase = nullptr;
  const void* n = nullptr;
  if (isBase != 1) {
    return (int)(0);
  }
  if (__d__value() != 15) {
    return (int)(0);
  }
  if (n != 3) {
    return (int)(0);
  }
  return (int)(1);
}

int runNewTests(void) {
  const void* a = __new__C(1);
  if (__a__getValue() != 1) {
    return (int)(0);
  }
  const void* p = __new__P(10);
  const void* v = __p__getValue();
  return 0;
}

int runCoutStressTests(void) {
  double coutAcc = 0;
  double i = 1;
  coutAcc = coutAcc + i;
  __console__log("[cout-test] tick");
  i++;
  coutAcc = coutAcc + i;
  __console__log("[cout-test] tick");
  i++;
  coutAcc = coutAcc + i;
  __console__log("[cout-test] tick");
  return 0;
}

int runForCoutTest(void) {
  double sum = 0;
  const double ratio = 1;
  {
    double i = 1;
    for (; i < 4; i++) {
      sum = sum + i;
      __console__log("[for-cout] tick");
    }
  }
  return 0;
}

int bubbleSort(int array) {
  const void* size = array.length;
  {
    double i = 0;
    for (; i < size - 1; i++) {
      {
        double j = 0;
        for (; j < size - i - 1; j++) {
          if (0) {
            const void* temp = nullptr;
            array = 0;
            array = temp;
          }
        }
      }
    }
  }
  return 0;
}

int runArrayStressTests(void) {
  __console__log("--- Array Stress (C-like) ---");
  const void* array = __maia_arr_literal0();
  array = 5;
  array = 2;
  array = 8;
  array = 1;
  array = 9;
  array = 3;
  array = 7;
  array = 4;
  array = 6;
  array = 0;
  bubbleSort(array);
  double pos5 = 1;
  double pos11 = 1;
  {
    double i = 0;
    for (; i < 10; i++) {
      if (0) {
        pos5 = i;
      }
      if (0) {
        pos11 = i;
      }
    }
  }
  double checksum = 0;
  {
    double i = 0;
    for (; i < 10; i++) {
      checksum = 0;
    }
  }
  __console__log("array checksum=" + checksum + " pos5=" + pos5 + " pos11=" + pos11);
  const void* array3dFlat = __maia_arr_literal0();
  {
    double i = 0;
    for (; i < 2; i++) {
      {
        double j = 0;
        for (; j < 3; j++) {
          {
            double k = 0;
            for (; k < 4; k++) {
              const void* idx = i * 12 + j * 4 + k;
              array3dFlat = idx;
            }
          }
        }
      }
    }
  }
  const void* v123 = nullptr;
  __console__log("array3d[1][2][3]=" + v123);
  const void* strings = __maia_arr_literal0();
  strings = "First string";
  strings = "Second string";
  strings = "Third string";
  double strChars = 0;
  {
    double i = 0;
    for (; i < 3; i++) {
      strChars = strChars + strings.length;
      __console__log(0);
    }
  }
  const void* points = __maia_arr_literal0();
  {
    double i = 0;
    for (; i < 5; i++) {
      points = __new__PointRec(i * 10, i * 20);
    }
  }
  const void* lastPoint = nullptr;
  __console__log("points[4]=(" + lastPoint.x + "," + lastPoint.y + ")");
  const void* matrix = __maia_arr_literal0();
  matrix = 1;
  matrix = 2;
  matrix = 3;
  matrix = 4;
  matrix = 5;
  matrix = 6;
  matrix = 7;
  matrix = 8;
  matrix = 9;
  matrix = 10;
  matrix = 11;
  matrix = 12;
  double diag = 0;
  {
    double i = 0;
    for (; i < 3; i++) {
      diag = 0;
    }
  }
  __console__log("diag=" + diag);
  if (checksum != 45) {
    return (int)(0);
  }
  if (pos5 != 5) {
    return (int)(0);
  }
  if (pos11 != 1) {
    return (int)(0);
  }
  if (v123 != 23) {
    return (int)(0);
  }
  if (strChars != 37) {
    return (int)(0);
  }
  if (lastPoint.x != 40 || lastPoint.y != 80) {
    return (int)(0);
  }
  if (diag != 18) {
    return (int)(0);
  }
  return (int)(1);
}

int runProgram(void) {
  __console__log("=== MaiaJS Comprehensive Runtime Baseline ===");
  const void* r1 = runClassTests();
  const void* r2 = runBoxTests();
  const void* r3 = runFunctionRefTests();
  const void* r4 = runInheritanceTests();
  const void* r5 = runNewTests();
  const void* r6 = runCoutStressTests();
  const void* r7 = runForCoutTest();
  const void* r8 = runArrayStressTests();
  __console__log("1. class/ctor/method=" + r1);
  __console__log("2. box/slot-index=" + r2);
  __console__log("3. function-ref dispatch=" + r3);
  __console__log("4. inheritance/instanceof/trunc=" + r4);
  __console__log("5. new/ctor=" + r5);
  __console__log("6. cout stress=" + r6);
  __console__log("7. for-loop with logging=" + r7);
  __console__log("8. robust arrays battery=" + r8);
  const void* failures = nullptr;
  if (failures == 0) {
    __console__log("ALL TESTS PASSED");
    return (int)(0);
  }
  __console__log("TESTS FAILED: " + failures);
  return (int)(1);
}

int main() {
  runProgram();
  return 0;
}
