#!/usr/bin/env bash
# build_all.sh — Transpile every C++98 test in the suite through the full
#                MaiaCpp → MaiaC pipeline, keeping intermediate artefacts.
#
# For each NN_category/*.cpp this script produces:
#   NN_category/<name>.c      — MaiaCpp C-translation (inspect line-by-line)
#   NN_category/<name>.wat    — MaiaC WAT output      (inspect line-by-line)
#   NN_category/dist/         — runnable WASM dist (node-runner.sh, *.wasm …)
#
# Usage (from anywhere):
#   bash /path/to/suite/build_all.sh [--verbose] [FILTER]
#
#   FILTER  optional substring — only build dirs whose name contains FILTER
#           e.g.  bash build_all.sh 04  → only 04_classes
#
# Exit code: 0 if every build succeeded, 1 if any failed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
MAIAJS_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd -P)"
PROJECTS_ROOT="$(cd "$MAIAJS_ROOT/.." && pwd -P)"

resolve_webcpp() {
    local local_path="$1"
    local sibling_path="$2"
    if [[ -f "$local_path" ]]; then
        echo "$local_path"
        return 0
    fi
    if [[ -f "$sibling_path" ]]; then
        echo "$sibling_path"
        return 0
    fi
    return 1
}

resolve_webjs() {
    local local_path="$1"
    local sibling_path="$2"
    if [[ -f "$local_path" ]]; then
        echo "$local_path"
        return 0
    fi
    if [[ -f "$sibling_path" ]]; then
        echo "$sibling_path"
        return 0
    fi
    return 1
}

WEBCPP="$(resolve_webcpp "$MAIAJS_ROOT/maiacpp/bin/webcpp.sh" "$PROJECTS_ROOT/maiacpp/bin/webcpp.sh" || true)"
WEBJS="$(resolve_webjs "$MAIAJS_ROOT/bin/webjs.sh" "$PROJECTS_ROOT/maiajs/bin/webjs.sh" || true)"

VERBOSE=0
FILTER=""
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=1 ;;
        *)            FILTER="$arg" ;;
    esac
done

if [[ -z "$WEBCPP" || ! -f "$WEBCPP" ]]; then
    echo "ERROR: webcpp.sh not found at: $WEBCPP" >&2
    exit 1
fi

if [[ -z "$WEBJS" || ! -f "$WEBJS" ]]; then
    echo "ERROR: webjs.sh not found at: $WEBJS" >&2
    exit 1
fi

PASS=0
FAIL=0
SKIP=0
JS_PASS=0
JS_FAIL=0
JS_UNSUPPORTED=0

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

build_one() {
    local src="$1"
    local dir
    dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.cpp}")"
    local c_out="${src%.cpp}.c"
    local wat_out="${src%.cpp}.wat"
    local dist_dir="$dir/dist"

    echo ""
    echo "==> $(basename "$dir")/$stem.cpp"

    local cmd=("$WEBCPP" "$src"
        --c-out   "$c_out"
        --wat-out "$wat_out"
        --dist    --out-dir "$dist_dir"
        --name    "$stem")

    if [[ "$VERBOSE" -eq 1 ]]; then
        "${cmd[@]}"
    else
        if ! "${cmd[@]}" 2>&1 | grep -E '^\[(webcpp|webc)\]|ERROR|error:' ; then
            true   # suppress noisy MaiaC progress lines
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    FAILED (exit $rc)"
        FAIL=$((FAIL + 1))
        return
    fi

    local size_wasm=0
    local wasm_file="${src%.cpp}.wasm"
    if [[ -f "$wasm_file" ]]; then
        size_wasm="$(wc -c < "$wasm_file")"
        # Keep dist self-contained for run_all.sh/node-runner.js default path.
        cp -f "$wasm_file" "$dist_dir/$stem.wasm"
    fi

    echo "    OK — C: $(basename "$c_out")  WAT: $(basename "$wat_out")  WASM: ${size_wasm}B"
    PASS=$((PASS + 1))
}

build_js() {
    local src="$1"
    local dir
    dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.js}")"
    local dist_dir="$dir/dist_js"

    echo ""
    echo "==> $(basename "$dir")/$stem.js"

    local cmd=("$WEBJS" "$src"
        --dist --out-dir "$dist_dir"
        --name "$stem")

    if [[ "$VERBOSE" -eq 1 ]]; then
        "${cmd[@]}"
    else
        if ! "${cmd[@]}" 2>&1 | grep -E '^\[(webjs|webcpp|webc)\]|ERROR|error:' ; then
            true
        fi
    fi

    local rc="${PIPESTATUS[0]:-${?}}"
    if [[ "$rc" -ne 0 ]]; then
        echo "    FAILED (exit $rc)"
        JS_FAIL=$((JS_FAIL + 1))
        return
    fi

    local size_wasm=0
    local runner_file="$dist_dir/node-runner.sh"
    local wasm_file="$dist_dir/$stem.wasm"
    if [[ -f "$wasm_file" && -f "$runner_file" ]]; then
        size_wasm="$(wc -c < "$wasm_file")"
    else
        echo "    SKIP — JS dist output missing (node-runner.sh or $stem.wasm)"
        SKIP=$((SKIP + 1))
        return
    fi

    echo "    OK — JS dist WASM: ${size_wasm}B"
    JS_PASS=$((JS_PASS + 1))
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    # Apply optional filter
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        build_one "$src"
    done

    for src in "$test_dir"*.js; do
        [[ -f "$src" ]] || continue
        if is_generated_webc_js "$src"; then
            stem="$(basename "${src%.js}")"
            echo ""
            echo "==> $(basename "$test_dir")/$stem.js"
            echo "    SKIP — generated webc artifact (unsupported source class)"
            JS_UNSUPPORTED=$((JS_UNSUPPORTED + 1))
            continue
        fi
        build_js "$src"
    done
done

echo ""
echo "========================================"
echo "Build complete: $PASS built, $FAIL failed, $SKIP skipped"
echo "JS build      : $JS_PASS built, $JS_FAIL failed"
echo "JS build      : $JS_UNSUPPORTED skipped as unsupported source class"
echo "========================================"

if [[ "$FAIL" -gt 0 || "$JS_FAIL" -gt 0 ]]; then
    exit 1
fi
