#!/usr/bin/env bash
# run_all.sh — Run suite through:
#   1) C++ path output validation (dist generated from *.cpp)
#   2) JS port output validation (dist_js generated from *.port.js/js_ports)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
FILTER="${1:-}"
WASM_TIMEOUT="${WASM_TIMEOUT:-10}"
STRICT="${STRICT:-1}"

PASS=0
FAIL=0
SKIP=0
JS_PASS=0
JS_FAIL=0
JS_SKIP=0
JS_NO_PORTS=0

run_timed() {
    local secs="$1"
    shift
    if command -v timeout >/dev/null 2>&1; then
        timeout "$secs" "$@"
    elif command -v gtimeout >/dev/null 2>&1; then
        gtimeout "$secs" "$@"
    else
        "$@"
    fi
}

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

is_js_port_file() {
    local src="$1"
    [[ -f "$src" ]] || return 1
    case "$(basename "$src")" in
        node-runner.js|browser-memory-file-store.js) return 1 ;;
    esac
    if is_generated_webc_js "$src"; then
        return 1
    fi
    return 0
}

collect_js_ports_for_dir() {
    local test_dir="$1"
    local src
    shopt -s nullglob
    for src in "$test_dir"*.port.js "$test_dir"js_ports/*.js; do
        is_js_port_file "$src" && printf '%s\n' "$src"
    done
    shopt -u nullglob
}

normalize_output() {
    printf '%s\n' "$1" \
        | LC_ALL=C tr -d '\000' \
        | awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}'
}

run_cpp_one() {
    local test_dir="$1"
    local stem="$2"
    local runner_sh="$test_dir/dist/node-runner.sh"
    local runner_js="$test_dir/dist/node-runner.js"
    local wasm_file="$test_dir/dist/$stem.wasm"
    if [[ ! -f "$wasm_file" ]]; then
        wasm_file="$test_dir/$stem.wasm"
    fi
    local expected="$test_dir/expected_output.txt"

    echo ""
    echo "--> $(basename "$test_dir")/$stem [cpp]"

    if [[ ! -f "$runner_sh" && ! -f "$runner_js" ]]; then
        echo "    SKIP — dist not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi
    if [[ ! -f "$wasm_file" ]]; then
        echo "    SKIP — wasm not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi

    local actual_raw
    if [[ -f "$runner_sh" ]]; then
        actual_raw="$(run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
    else
        actual_raw="$(run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" 2>/dev/null)" || true
    fi

    local actual
    actual="$(printf '%s\n' "$actual_raw" | sed '/^\[node-runner\] program returned:/d')"
    local actual_norm
    actual_norm="$(normalize_output "$actual")"

    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$actual_norm") <(printf '%s\n' "$expected_norm") > /dev/null 2>&1; then
            echo "    PASS"
            PASS=$((PASS + 1))
        else
            echo "    FAIL — output mismatch"
            FAIL=$((FAIL + 1))
        fi
    else
        local last
        last="$(printf '%s\n' "$actual" | tail -n1)"
        if [[ "$last" == "ALL PASS" ]]; then
            echo "    PASS (no expected_output.txt — last line: ALL PASS)"
            PASS=$((PASS + 1))
        else
            echo "    SKIP — no expected_output.txt and no ALL PASS marker"
            SKIP=$((SKIP + 1))
        fi
    fi
}

run_js_port_one() {
    local src="$1"
    local test_dir
    test_dir="$(dirname "$src")"
    local stem
    stem="$(basename "${src%.js}")"
    local runner_sh="$test_dir/dist_js/node-runner.sh"
    local runner_js="$test_dir/dist_js/node-runner.js"
    local wasm_file="$test_dir/dist_js/$stem.wasm"
    local expected="$test_dir/${stem}.js_expected_output.txt"

    echo ""
    echo "--> $(basename "$test_dir")/$stem [js-port]"

    if [[ ! -f "$runner_sh" && ! -f "$runner_js" ]]; then
        echo "    SKIP — JS port dist not found (run build_all.sh first)"
        JS_SKIP=$((JS_SKIP + 1))
        return
    fi
    if [[ ! -f "$wasm_file" ]]; then
        echo "    SKIP — JS port wasm not found"
        JS_SKIP=$((JS_SKIP + 1))
        return
    fi

    local actual_raw
    if [[ -f "$runner_sh" ]]; then
        actual_raw="$(run_timed "$WASM_TIMEOUT" bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
    else
        actual_raw="$(run_timed "$WASM_TIMEOUT" node "$runner_js" "$wasm_file" 2>/dev/null)" || true
    fi

    local actual
    actual="$(printf '%s\n' "$actual_raw" | sed '/^\[node-runner\] program returned:/d')"
    local actual_norm
    actual_norm="$(normalize_output "$actual")"

    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$actual_norm") <(printf '%s\n' "$expected_norm") > /dev/null 2>&1; then
            echo "    PASS"
            JS_PASS=$((JS_PASS + 1))
        else
            echo "    FAIL — output mismatch"
            JS_FAIL=$((JS_FAIL + 1))
        fi
    else
        local last
        last="$(printf '%s\n' "$actual" | tail -n1)"
        if [[ "$last" == "ALL PASS" ]]; then
            echo "    PASS (no js_expected_output.txt — last line: ALL PASS)"
            JS_PASS=$((JS_PASS + 1))
        else
            echo "    SKIP — no js_expected_output.txt and no ALL PASS marker"
            JS_SKIP=$((JS_SKIP + 1))
        fi
    fi
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        run_cpp_one "$test_dir" "$stem"
    done

done

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    local_has_port=0
    while IFS= read -r src; do
        [[ -n "$src" ]] || continue
        local_has_port=1
        run_js_port_one "$src"
    done < <(collect_js_ports_for_dir "$test_dir")

    if [[ "$local_has_port" -eq 0 ]]; then
        JS_NO_PORTS=$((JS_NO_PORTS + 1))
    fi

done

echo ""
echo "========================================"
echo "C++ results : $PASS passed  /  $FAIL failed  /  $SKIP skipped"
echo "JS ports    : $JS_PASS passed  /  $JS_FAIL failed  /  $JS_SKIP skipped"
echo "JS ports    : $JS_NO_PORTS dirs without JS ports"
echo "========================================"

if [[ "$FAIL" -gt 0 || "$JS_FAIL" -gt 0 ]]; then
    exit 1
fi

if [[ "$STRICT" == "1" && ( "$SKIP" -gt 0 || "$JS_SKIP" -gt 0 ) ]]; then
    echo "STRICT mode: failing because at least one test was skipped."
    exit 1
fi
