#!/usr/bin/env bash
# run_all.sh — Execute every compiled WASM test and compare output.
#
# For each NN_category/<name>.cpp it:
#   1. Runs  dist/node-runner.sh  (fails with SKIP if not yet built)
#   2. Diffs actual output against expected_output.txt
#   3. If no expected file exists, checks that the last line is "ALL PASS"
#
# Usage (from anywhere):
#   bash /path/to/suite/run_all.sh [FILTER]
#
#   FILTER  optional substring — only test dirs whose name contains FILTER
#
# Exit code: 0 if every test passed, 1 if any failed.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

FILTER="${1:-}"
STRICT="${STRICT:-1}"

PASS=0
FAIL=0
SKIP=0
FAIL_SEMANTIC=0
FAIL_EXPECTED=0
JS_PASS=0
JS_FAIL=0
JS_SKIP=0
JS_UNSUPPORTED=0

is_generated_webc_js() {
    local src="$1"
    grep -q "Auto-generated by webc" "$src" 2>/dev/null
}

normalize_output() {
    printf '%s\n' "$1" \
    | LC_ALL=C tr -d '\000' \
        | awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}'
}

run_one_js() {
    local test_dir="$1"
    local stem="$2"
    local expected="$test_dir/expected_output.txt"
    local runner_sh="$test_dir/dist_js/node-runner.sh"
    local runner_js="$test_dir/dist_js/node-runner.js"
    local wasm_file="$test_dir/dist_js/$stem.wasm"
    local src_js="$test_dir/$stem.js"
    if [[ -f "$src_js" ]] && is_generated_webc_js "$src_js"; then
        echo "    SKIP — generated webc artifact (unsupported source class)"
        JS_UNSUPPORTED=$((JS_UNSUPPORTED + 1))
        return
    fi


    echo ""
    echo "--> $(basename "$test_dir")/$stem [js]"

    if [[ ! -f "$runner_sh" && ! -f "$runner_js" ]]; then
        echo "    SKIP — JS dist not found (run build_all.sh first)"
        JS_SKIP=$((JS_SKIP + 1))
        return
    fi
    if [[ ! -f "$wasm_file" ]]; then
        echo "    SKIP — JS wasm not found (run build_all.sh first)"
        JS_SKIP=$((JS_SKIP + 1))
        return
    fi

    local actual_raw
    if [[ -f "$runner_sh" ]]; then
        actual_raw="$(bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
    else
        actual_raw="$(node "$runner_js" "$wasm_file" 2>/dev/null)" || true
    fi
    local actual
    actual="$(printf '%s\n' "$actual_raw" | sed '/^\[node-runner\] program returned:/d')"
    local actual_norm
    actual_norm="$(normalize_output "$actual")"

    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$actual_norm") <(printf '%s\n' "$expected_norm") > /dev/null 2>&1; then
            echo "    PASS"
            JS_PASS=$((JS_PASS + 1))
        else
            echo "    FAIL — output mismatch"
            echo "    ┌── expected ──────────────────────────────────────"
            printf '%s\n' "$expected_norm" | sed 's/^/    │ /'
            echo "    ├── actual ────────────────────────────────────────"
            printf '%s\n' "$actual_norm" | sed 's/^/    │ /'
            echo "    └─────────────────────────────────────────────────"
            JS_FAIL=$((JS_FAIL + 1))
        fi
    else
        local last
        last="$(printf '%s\n' "$actual" | tail -n1)"
        if [[ "$last" == "ALL PASS" ]]; then
            echo "    PASS (no expected_output.txt — last line: ALL PASS)"
            JS_PASS=$((JS_PASS + 1))
        else
            echo "    WARN — no expected_output.txt; last line: $last"
            JS_SKIP=$((JS_SKIP + 1))
        fi
    fi
}

run_one() {
    local test_dir="$1"
    local stem="$2"
    local runner_sh="$test_dir/dist/node-runner.sh"
    local runner_js="$test_dir/dist/node-runner.js"
    local wasm_file="$test_dir/dist/$stem.wasm"
    if [[ ! -f "$wasm_file" ]]; then
        wasm_file="$test_dir/$stem.wasm"
    fi
    local expected="$test_dir/expected_output.txt"
    local generated_c="$test_dir/$stem.c"

    echo ""
    echo "--> $(basename "$test_dir")/$stem"

    if [[ ! -f "$runner_sh" && ! -f "$runner_js" ]]; then
        echo "    SKIP — dist not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi
    if [[ ! -f "$wasm_file" ]]; then
        echo "    SKIP — wasm not found (run build_all.sh first)"
        SKIP=$((SKIP + 1))
        return
    fi

    local actual_raw
    if [[ -f "$runner_sh" ]]; then
        actual_raw="$(bash "$runner_sh" "$wasm_file" 2>/dev/null)" || true
    else
        actual_raw="$(node "$runner_js" "$wasm_file" 2>/dev/null)" || true
    fi
    local actual
    actual="$(printf '%s\n' "$actual_raw" | sed '/^\[node-runner\] program returned:/d')"
    local actual_norm
    actual_norm="$(normalize_output "$actual")"

    if [[ -f "$expected" ]]; then
        local expected_norm
        expected_norm="$(awk 'NF{last=NR} {lines[NR]=$0} END{for(i=1;i<=last;i++) print lines[i]}' "$expected")"
        if diff <(printf '%s\n' "$actual_norm") <(printf '%s\n' "$expected_norm") > /dev/null 2>&1; then
            echo "    PASS"
            PASS=$((PASS + 1))
        else
            local classification="unknown"
            if [[ -f "$generated_c" ]]; then
                if grep -q "main: stub-fallback" "$generated_c"; then
                    classification="semantic-gap"
                    FAIL_SEMANTIC=$((FAIL_SEMANTIC + 1))
                else
                    classification="expected-drift"
                    FAIL_EXPECTED=$((FAIL_EXPECTED + 1))
                fi
            fi
            echo "    FAIL — output mismatch"
            echo "    Classificacao: $classification"
            echo "    ┌── expected ──────────────────────────────────────"
            printf '%s\n' "$expected_norm" | sed 's/^/    │ /'
            echo "    ├── actual ────────────────────────────────────────"
            printf '%s\n' "$actual_norm" | sed 's/^/    │ /'
            echo "    └─────────────────────────────────────────────────"
            FAIL=$((FAIL + 1))
        fi
    else
        # No reference file: just check last line
        local last
        last="$(printf '%s\n' "$actual" | tail -n1)"
        if [[ "$last" == "ALL PASS" ]]; then
            echo "    PASS (no expected_output.txt — last line: ALL PASS)"
            PASS=$((PASS + 1))
        else
            echo "    WARN — no expected_output.txt; last line: $last"
            printf '%s\n' "$actual" | sed 's/^/    > /'
            SKIP=$((SKIP + 1))
        fi
    fi
}

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.cpp; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.cpp}")"
        run_one "$test_dir" "$stem"
    done
done

for test_dir in "$SCRIPT_DIR"/*/; do
    [[ -d "$test_dir" ]] || continue
    dir_name="$(basename "$test_dir")"
    [[ -z "$FILTER" || "$dir_name" == *"$FILTER"* ]] || continue

    for src in "$test_dir"*.js; do
        [[ -f "$src" ]] || continue
        stem="$(basename "${src%.js}")"
        run_one_js "$test_dir" "$stem"
    done
done

echo ""
echo "========================================"
echo "Results: $PASS passed  /  $FAIL failed  /  $SKIP skipped"
echo "JS     : $JS_PASS passed  /  $JS_FAIL failed  /  $JS_SKIP skipped"
echo "JS     : $JS_UNSUPPORTED skipped as unsupported source class"
echo "Failed breakdown: semantic-gap=$FAIL_SEMANTIC  /  expected-drift=$FAIL_EXPECTED"
echo "========================================"

if [[ "$FAIL" -gt 0 || "$JS_FAIL" -gt 0 ]]; then
    exit 1
fi

if [[ "$STRICT" == "1" && ( "$SKIP" -gt 0 || "$JS_SKIP" -gt 0 ) ]]; then
    echo "STRICT mode: failing because at least one test was skipped."
    exit 1
fi
