// Auto-generated by ecmascript-compiler.js
// Source: test.js
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log
// Host-call map: console.log -> __console__log

extern void __console__log(const char*);

int main() {
  __console__log("=== MaiaJS Dist Smoke Test ===");
  double a = 10;
  double b = 20;
  void* sum = a + b;
  void* diff = b - a;
  void* product = a * 3;
  __console__log("sum=" + sum);
  __console__log("diff=" + diff);
  __console__log("product=" + product);
  __console__log("status=ok");
  return 0;
}
